# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewctl < Formula
  desc "SyntheticBrew engine config-as-code apply tool"
  homepage "https://syntheticbrew.ai"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.6.0/brewctl_0.6.0_darwin_amd64.tar.gz"
      sha256 "2db1291c8a63e4601245c13e59ecf983ac0aabd40568d634d3f9834e3ad1da43"

      define_method(:install) do
        bin.install "brewctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.6.0/brewctl_0.6.0_darwin_arm64.tar.gz"
      sha256 "27f53540dcdb0285fa86a0ada92c71b4a0e514c8f9f65d7aab869aeae8264a33"

      define_method(:install) do
        bin.install "brewctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.6.0/brewctl_0.6.0_linux_amd64.tar.gz"
      sha256 "b28cbe874e7a911ac589295167dcec05a55a0e3c4ac74e2dc57e7f28726a86d5"
      define_method(:install) do
        bin.install "brewctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.6.0/brewctl_0.6.0_linux_arm64.tar.gz"
      sha256 "ceac07084b02956e182f21becd0c686814180a26349d15d76d26500ae5c203a3"
      define_method(:install) do
        bin.install "brewctl"
      end
    end
  end

  test do
    system "#{bin}/brewctl version"
  end
end
