# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brewctl < Formula
  desc "SyntheticBrew engine config-as-code apply tool"
  homepage "https://syntheticbrew.ai"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.3.0/brewctl_0.3.0_darwin_amd64.tar.gz"
      sha256 "35eb7c25504e0f8c4820bfbf0be5705ccc239e7ec2a6234d8ae117a9cdc215a5"

      define_method(:install) do
        bin.install "brewctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.3.0/brewctl_0.3.0_darwin_arm64.tar.gz"
      sha256 "8b8ff1dfc75e370fc86c9549044ddbdb9b5a36858e799b85e7715c40833e8203"

      define_method(:install) do
        bin.install "brewctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.3.0/brewctl_0.3.0_linux_amd64.tar.gz"
      sha256 "4285f2abbb1648644f7a38ecf0a7fb13027a2dc3a6896e0ffe8fe73dc2136c3a"
      define_method(:install) do
        bin.install "brewctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/syntheticinc/syntheticbrew-brewctl/releases/download/v0.3.0/brewctl_0.3.0_linux_arm64.tar.gz"
      sha256 "02e0d6b1357fc5133524c60020053daa404c5b86a143ffb51a0742b18397aaed"
      define_method(:install) do
        bin.install "brewctl"
      end
    end
  end

  test do
    system "#{bin}/brewctl version"
  end
end
